/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303039",
        "surface-bright": "#393842",
        "background": "#13131b",
        "on-primary-fixed": "#05006c",
        "primary-fixed-dim": "#c0c1ff",
        "error-container": "#93000a",
        "primary": "#c0c1ff",
        "on-secondary": "#003641",
        "on-tertiary-fixed-variant": "#733500",
        "secondary-fixed-dim": "#41d7f9",
        "tertiary-container": "#b55700",
        "on-secondary-fixed-variant": "#004e5d",
        "surface-dim": "#13131b",
        "on-surface": "#e4e1ed",
        "on-secondary-fixed": "#001f26",
        "surface-primary": "#11161D",
        "secondary-container": "#00bedf",
        "outline-variant": "#464555",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#2c2cc3",
        "tertiary-fixed": "#ffdbc8",
        "on-tertiary-fixed": "#311300",
        "on-primary": "#0e00aa",
        "inverse-primary": "#474adb",
        "on-tertiary": "#512300",
        "secondary-fixed": "#adecff",
        "success": "#22C55E",
        "on-error-container": "#ffdad6",
        "on-background": "#e4e1ed",
        "surface-elevated": "#202935",
        "on-primary-container": "#f9f6ff",
        "surface-tint": "#c0c1ff",
        "outline": "#908fa0",
        "surface-container-low": "#1b1b23",
        "error": "#EF4444",
        "primary-container": "#5b5fef",
        "tertiary-fixed-dim": "#ffb689",
        "surface-variant": "#34343d",
        "on-error": "#690005",
        "surface-secondary": "#181F28",
        "surface-container-high": "#292932",
        "inverse-surface": "#e4e1ed",
        "surface": "#13131b",
        "bg-base": "#090B0F",
        "on-tertiary-container": "#fff6f2",
        "surface-container-lowest": "#0d0d16",
        "on-secondary-container": "#004856",
        "tertiary": "#ffb689",
        "secondary": "#45dafc",
        "warning": "#F59E0B",
        "surface-container": "#1f1f28",
        "surface-container-highest": "#34343d",
        "on-surface-variant": "#c6c5d7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xs": "4px",
        "max-width": "1440px",
        "margin": "24px",
        "gutter": "16px",
        "xl": "32px",
        "base": "8px",
        "2xl": "48px",
        "md": "16px",
        "3xl": "64px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-default": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "title-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-default": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
